# Generated by Django 2.2 on 2020-01-27 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlanNettoyage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('id_collaborateur', models.FloatField(blank=True, null=True)),
                ('first_name_collaborateur', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name_collaborateur', models.CharField(blank=True, max_length=70, null=True)),
            ],
        ),
    ]
