# Generated by Django 2.2 on 2020-01-27 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_nettoyage', '0002_plannettoyage_piece'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plannettoyage',
            name='title',
        ),
        migrations.AddField(
            model_name='plannettoyage',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plannettoyage',
            name='id_plan_nettoyage',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
