# Generated by Django 2.2 on 2020-01-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan_nettoyage', '0003_auto_20200127_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='plannettoyage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
