# Generated by Django 2.2 on 2020-01-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_piece', models.FloatField(blank=True, null=True)),
                ('name_piece', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
