# Generated by Django 2.2 on 2020-01-19 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appareil', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appareil',
            old_name='localisation',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='appareil',
            old_name='nom',
            new_name='name',
        ),
    ]
