# Generated by Django 2.2 on 2020-01-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190407_2016'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userInfosSaved',
        ),
    ]
