# Generated by Django 2.2 on 2020-01-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controle_temperature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controletemperature',
            name='type_nourriture',
        ),
    ]
