# Generated by Django 2.2 on 2020-01-19 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ControleReception',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('id_collaborateur', models.FloatField(blank=True, null=True)),
                ('id_fournisseur', models.FloatField(blank=True, null=True)),
                ('first_name_collaborateur', models.CharField(blank=True, max_length=70, null=True)),
                ('last_name_collaborateur', models.CharField(blank=True, max_length=70, null=True)),
                ('name_fournisseur', models.CharField(blank=True, max_length=70, null=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('periode_reception', models.CharField(blank=True, max_length=70, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('user_username', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
