# Generated by Django 2.2 on 2020-01-19 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlereception',
            name='id_controle_reception',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
