# Generated by Django 2.2 on 2020-01-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_reception', '0002_controlereception_id_controle_reception'),
    ]

    operations = [
        migrations.AddField(
            model_name='controlereception',
            name='type_nourriture',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
